infrastructureServices:
  - name: "wkl3nk Packages on github"
    url: "https://maven.pkg.github.com/wkl3nk/simple-maven-java<"
    usernameSecret: "github-wkl3nk-username"
    passwordSecret: "github-wkl3nk-token"
environmentDefinitions:
  maven:
    - service: "wkl3nk Packages on github"
      id: "wkl3nk-github-packages"
